language: node_js
node_js:
    - "node"
before_install:
  - npm install -g istanbul
install:
  - npm install -g codecov
script:
  - istanbul cover tests/*.test.js --reporter lcovonly -- -R spec
  - codecov
