language: node_js
node_js:
    - "node"
cache:
    directories:
        - "node_modules"
services:
  - postgresql
before_install:
    - npm install -g codecov
before_script:
    - psql -c 'create database travis_ci_test;' -U postgres
script:
    - npm test && npm run coverage
after_success:
    - codecov
